version: '3.7'

networks:
  pterodactyl:
    external: true
  local:
    external: false

services:

  mysql:
    image: mariadb:10.5
    restart: always
    networks:
      - local
    env_file:
      - .env
    volumes:
      - ${DATA_DIR}/mariadb:/var/lib/mysql

  panel:
    image: ccarney16/pterodactyl-panel:v1.0.1
    restart: always
    networks:
      - local
      - pterodactyl
    env_file:
      - .env
    depends_on:
      - cache
    environment:
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DATA_DIR}/panel:/data
    labels:
      - "traefik.http.routers.panel.rule=Host(`${SUBDOMAIN_PANEL}.${DOMAIN}`)"
      - "traefik.http.routers.panel.tls=true"

  worker:
    image: ccarney16/pterodactyl-panel:v1.0.1
    restart: always
    command: p:worker
    env_file:
      - .env
    networks:
      - local
    volumes:
      - ${DATA_DIR}/panel:/data

  cron:
    image: ccarney16/pterodactyl-panel:v1.0.1
    restart: always
    command: p:cron
    env_file:
      - .env
    networks:
      - local
    volumes:
      - ${DATA_DIR}/panel:/data

  cache:
    image: redis:alpine
    restart: always
    networks:
      - local

  daemon:
    image: ccarney16/pterodactyl-daemon:v1.0.0
    ports:
      - 2022:2022
    privileged: true
    restart: always
    networks:
      - local
      - pterodactyl
    working_dir: ${DATA_DIR_DAEMON}
    volumes:
      - ${DATA_DIR_DAEMON}:${DATA_DIR_DAEMON}
      - ${DATA_DIR}/daemon:/etc/pterodactyl
      - /etc/timezone:/etc/timezone:ro
      - /tmp/pterodactyl:/tmp/pterodactyl
      - ${DAEMON_DOCKER_ROOT:-/var/lib/docker}:${DAEMON_DOCKER_ROOT:-/var/lib/docker}
      - ${DAEMON_DOCKER_SOCKET:-/var/run/docker.sock}:${DAEMON_DOCKER_SOCKET:-/var/run/docker.sock}
    labels:
      - "traefik.http.routers.daemon.rule=Host(`${SUBDOMAIN_DAEMON}.${DOMAIN}`)"
      - "traefik.http.routers.daemon.tls=true"
      - "traefik.http.services.daemon.loadbalancer.server.port=443"
      - "traefik.http.middlewares.daemon-header.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.daemon-header.headers.accesscontrolalloworigin=${SUBDOMAIN_PANEL}.${DOMAIN}"
      - "traefik.http.middlewares.daemon-header.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.daemon-header.headers.addvaryheader=true"

